[tool.poetry]
name = "coworker-ai"
version = "0.1.0"
description = "Helpful AI assistant for my daily routines"
authors = ["Yevhen Dyachenko"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "src", from = "."}
]

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.0.6"
gradio = "^5.0.0"
llama-index-vector-stores-chroma = "^0.1.9"
llama-index = "^0.10.50"
llama-index-llms-lmstudio = "^0.1.0"
fastapi = "^0.111.0"
pytest = "^8.2.2"
chromadb = "^0.5.3"
llama-index-storage-kvstore-redis = "^0.1.5"
llama-index-retrievers-bm25 = "^0.2.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Add scripts
[tool.poetry.scripts]
gradio_server = "src.ui.entrypoints.gradio_command:app"
uvicorn_server = "src.ui.entrypoints.mounted_command:app"

# Add pytest configuration
[tool.pytest.ini_options]
addopts = "-v --cov=src --cov-report=term-missing"
testpaths = ["tests"]
markers = [
    "unit: mark a test as a unit test",
    "integration: mark a test as an integration test",
]